-- Thêm 11 nguồn tin ngành điện phát hiện bị thiếu khi đối chiếu với tóm tắt thủ công ngày 21/04/2026.
-- Mẫu URL bài viết được phân tích từ list thủ công; regex filter chỉ bài có keyword "dien"/"nang-luong"/"evn"/"bess"
-- trong slug để tránh lấy bài không liên quan khi quét từ trang chủ.

INSERT INTO public.electricity_sources (name, base_url, list_url, feed_type, list_link_pattern, article_content_selector, category) VALUES
('Tuổi Trẻ',              'https://tuoitre.vn',               'https://tuoitre.vn/tag/nganh-dien.html',       'html_list', '/[^/]*(?:dien|nang-luong|evn|bess)[^/]*-\d{10,}\.htm',       'div.detail-content, article.main-content-body, div.content-detail, article', 'bao-chi'),
('Báo Đấu Thầu',          'https://baodauthau.vn',            'https://baodauthau.vn',                        'html_list', '/[^/]*(?:dien|nang-luong|evn|bess)[^/]*-post\d+\.html',      'div.article-content, article, div.content, div.detail-content',              'bao-chi'),
('Mekong Asean',          'https://mekongasean.vn',           'https://mekongasean.vn',                       'html_list', '/[^/]*(?:dien|nang-luong|evn|bess)[^/]*-\d+\.html',          'div.article-content, article, div.content, div.detail-content',              'bao-chi'),
('Báo Quảng Ninh',        'https://baoquangninh.vn',          'https://baoquangninh.vn',                      'html_list', '/[^/]*(?:dien|nang-luong|evn|bess)[^/]*-\d+\.html',          'div.article-content, article, div.content, div.detail-content',              'bao-chi'),
('Diễn đàn Doanh nghiệp', 'https://diendandoanhnghiep.vn',    'https://diendandoanhnghiep.vn',                'html_list', '/[^/]*(?:dien|nang-luong|evn|bess|luu-tru|pin)[^/]*-\d+\.html','div.article-content, article, div.content, div.detail',                     'doanh-nghiep'),
('Saigon Times',          'https://thesaigontimes.vn',        'https://thesaigontimes.vn',                    'html_list', '/[a-z0-9-]*(?:dien|nang-luong|evn|bess)[a-z0-9-]*/$',        'div.article-content, article, div.entry-content, div.content',               'bao-chi'),
('VOV',                   'https://vov.vn',                   'https://vov.vn',                               'html_list', '/[^/]+/[^/]*(?:dien|nang-luong|evn|bess)[^/]*-post\d+\.vov', 'div.article-content, article, div.post-content, div.content',                'bao-chi'),
('Tin Nhanh Chứng Khoán', 'https://www.tinnhanhchungkhoan.vn','https://www.tinnhanhchungkhoan.vn',            'html_list', '/[^/]*(?:dien|nang-luong|evn|bess)[^/]*-post\d+\.html',      'div.article-content, article, div.content, div.detail',                      'bao-chi'),
('Doanh nghiệp Hội nhập', 'https://doanhnghiephoinhap.vn',    'https://doanhnghiephoinhap.vn',                'html_list', '/[^/]*(?:dien|nang-luong|evn|bess)[^/]*-\d+\.html',          'div.article-content, article, div.content',                                  'doanh-nghiep'),
('The Leader',            'https://theleader.vn',             'https://theleader.vn',                         'html_list', '/[^/]*(?:dien|nang-luong|evn|bess)[^/]*-d\d+\.html',         'div.article-content, article, div.content',                                  'bao-chi'),
('Báo Quốc Tế',           'https://baoquocte.vn',             'https://baoquocte.vn',                         'html_list', '/[^/]*(?:dien|nang-luong|evn|bess|hat-nhan)[^/]*-\d+\.html', 'div.article-content, article, div.content',                                  'bao-chi');
